name: Build and deploy API app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: "RabbitMqProductAPI"
      PROJECT_NAME: "RabbitMqProductAPI"
      DOTNET_VERSION: "9.x"
      DOTNET_EF_VERSION: "9.0.1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.PROJECT_FOLDER}}/myapp

      - name: install dotnet ef
        run: dotnet tool install -g dotnet-ef --version ${{env.DOTNET_EF_VERSION}}

      - name: dotnet bundle migration
        run: dotnet ef migrations bundle --runtime linux-x64 -p ${{env.PROJECT_FOLDER}}/${{env.PROJECT_NAME}}.csproj -o ${{env.PROJECT_FOLDER}}/myapp/migrate

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.PROJECT_FOLDER}}/myapp
