name: Build and deploy API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0 # Remplacez par la version de .NET utilisée

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Publish project
        run: dotnet publish --no-build --configuration Release --output ./output

      - name: Install EF Tools
        run: dotnet tool install --global dotnet-ef

      - name: Apply database migrations
        env:
          DOTNET_ROOT: /usr/share/dotnet
        run: dotnet ef database update

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: api-build
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api-build
